/**
 * First-class outbound tools for the Claude Code CLI harness, via a bundled MCP
 * server. The strengthened system-prompt routing (outbound-routing.ts) tells the
 * agent to curl the daemon — but a prompt is advisory, and the harness has talked
 * itself out of it ("No SMS tool available in this setup", then told the user to
 * send it themselves). A real MCP tool can't be rationalized away: `tools/call`
 * is a structured action, not prose.
 *
 * The server is a tiny stdio JSON-RPC proxy — it owns NO logic. Each tool POSTs
 * to the SAME trust-gated daemon endpoint the curl path uses (/messagebee/send,
 * /mailbee/send, /mailbee/draft), so the allowlist/trust gate stays the single
 * server-side source of truth regardless of caller. We embed the server as a
 * string and write it to ~/.hivematrix/mcp at spawn time (idempotent), so it
 * works identically in a dev run and inside the packaged bundle — no separate
 * file for the bundler to miss.
 */

import { writeFileSync, readFileSync, mkdirSync } from "fs";
import { homedir } from "os";
import { join } from "path";

/** MCP server name → Claude namespaces its tools as `mcp__<name>__<tool>`. */
export const OUTBOUND_MCP_SERVER_NAME = "hivematrix";

/** The tool names to pass to `--allowedTools` so they auto-approve (gate is server-side). */
export const OUTBOUND_MCP_TOOL_NAMES = [
  `mcp__${OUTBOUND_MCP_SERVER_NAME}__send_imessage`,
  `mcp__${OUTBOUND_MCP_SERVER_NAME}__send_email`,
  `mcp__${OUTBOUND_MCP_SERVER_NAME}__draft_email`,
];

// Bump when OUTBOUND_MCP_SERVER_JS changes so the on-disk copy is rewritten.
const SERVER_VERSION = "2";

// The stdio MCP server (CommonJS, run by the bundled node). Deliberately avoids
// template literals / ${} so it nests cleanly in this TS template string. Speaks
// newline-delimited JSON-RPC 2.0 (the MCP stdio framing) and proxies tool calls
// to the daemon's loopback outbound endpoints with the daemon auth token.
export const OUTBOUND_MCP_SERVER_JS = [
  "// HiveMatrix outbound MCP server (stdio) — generated by outbound-mcp.ts. Do not edit.",
  '"use strict";',
  'var fs = require("fs"), os = require("os"), path = require("path"), http = require("http");',
  'var PORT = process.env.HIVE_DAEMON_PORT || "3747";',
  "function token() {",
  '  try { return fs.readFileSync(path.join(os.homedir(), ".hivematrix", "auth-token"), "utf8").trim(); }',
  '  catch (e) { return ""; }',
  "}",
  "function post(route, fields) {",
  "  return new Promise(function (resolve) {",
  "    var pairs = [];",
  "    for (var k in fields) { if (fields[k] != null && fields[k] !== '') pairs.push(encodeURIComponent(k) + '=' + encodeURIComponent(fields[k])); }",
  '    var body = pairs.join("&");',
  "    var req = http.request(",
  '      { host: "127.0.0.1", port: PORT, path: route, method: "POST",',
  '        headers: { "Content-Type": "application/x-www-form-urlencoded",',
  '                   "Content-Length": Buffer.byteLength(body),',
  '                   "Authorization": "Bearer " + token() } },',
  '      function (res) { var d = ""; res.on("data", function (c) { d += c; }); res.on("end", function () { resolve(d || "{}"); }); }',
  "    );",
  '    req.on("error", function (e) { resolve(JSON.stringify({ ok: false, message: "daemon unreachable: " + (e && e.message) })); });',
  "    req.write(body); req.end();",
  "  });",
  "}",
  "var TOOLS = [",
  '  { name: "send_imessage",',
  '    description: "Send an SMS/iMessage to the operator or an allowlisted contact via HiveMatrix Message Lane. Use this whenever a message should be texted — never tell the user no SMS tool exists or to send it themselves. Only allowlisted handles are accepted; a refusal comes back as a clear message to relay.",',
  '    inputSchema: { type: "object", properties: { to: { type: "string", description: "Phone number or iMessage handle (e.g. +15135550000)" }, text: { type: "string", description: "Message body" } }, required: ["to", "text"] } },',
  '  { name: "send_email",',
  '    description: "Send an email via HiveMatrix Mail Lane (Apple Mail). Sends only to trusted recipients; an untrusted recipient is saved as a draft for approval and the result says so. Use this to actually send — do not improvise with osascript or a Gmail integration.",',
  '    inputSchema: { type: "object", properties: { to: { type: "string" }, subject: { type: "string" }, body: { type: "string" } }, required: ["to", "body"] } },',
  '  { name: "draft_email",',
  '    description: "Save an email as a draft in Apple Mail (never sends) via HiveMatrix Mail Lane, for the operator to review and send.",',
  '    inputSchema: { type: "object", properties: { to: { type: "string" }, subject: { type: "string" }, body: { type: "string" } }, required: ["to", "body"] } }',
  "];",
  "function callTool(name, a) {",
  '  if (name === "send_imessage") return post("/messagebee/send", { to: a.to, text: a.text });',
  '  if (name === "send_email") return post("/mailbee/send", { to: a.to, subject: a.subject, body: a.body });',
  '  if (name === "draft_email") return post("/mailbee/draft", { to: a.to, subject: a.subject, body: a.body });',
  '  return Promise.resolve(JSON.stringify({ ok: false, message: "unknown tool: " + name }));',
  "}",
  "function send(msg) { process.stdout.write(JSON.stringify(msg) + String.fromCharCode(10)); }",
  "function handle(line) {",
  "  var msg; try { msg = JSON.parse(line); } catch (e) { return; }",
  "  var id = msg.id, method = msg.method;",
  '  if (method === "initialize") {',
  '    send({ jsonrpc: "2.0", id: id, result: { protocolVersion: (msg.params && msg.params.protocolVersion) || "2025-06-18", capabilities: { tools: {} }, serverInfo: { name: "hivematrix", version: "1.0.0" } } });',
  "    return;",
  "  }",
  '  if (method === "notifications/initialized" || method === "initialized") return;',
  '  if (method === "ping") { send({ jsonrpc: "2.0", id: id, result: {} }); return; }',
  '  if (method === "tools/list") { send({ jsonrpc: "2.0", id: id, result: { tools: TOOLS } }); return; }',
  '  if (method === "tools/call") {',
  "    var p = msg.params || {};",
  "    Promise.resolve(callTool(p.name, p.arguments || {})).then(function (out) {",
  '      send({ jsonrpc: "2.0", id: id, result: { content: [{ type: "text", text: out }] } });',
  '    }).catch(function (e) { send({ jsonrpc: "2.0", id: id, result: { content: [{ type: "text", text: JSON.stringify({ ok: false, message: String(e && e.message || e) }) }], isError: true } }); });',
  "    return;",
  "  }",
  '  if (id !== undefined && id !== null) send({ jsonrpc: "2.0", id: id, error: { code: -32601, message: "method not found: " + method } });',
  "}",
  'var buf = "";',
  'process.stdin.setEncoding("utf8");',
  'process.stdin.on("data", function (chunk) {',
  "  buf += chunk; var idx;",
  '  while ((idx = buf.indexOf(String.fromCharCode(10))) >= 0) {',
  "    var line = buf.slice(0, idx).trim(); buf = buf.slice(idx + 1);",
  "    if (line) handle(line);",
  "  }",
  "});",
  'process.stdin.on("end", function () { process.exit(0); });',
].join("\n");

/** Directory holding the generated server + the mcp-config we hand to Claude. */
function mcpDir(): string {
  return join(homedir(), ".hivematrix", "mcp");
}

/** Write the server to disk if missing/stale; return its absolute path. Idempotent. */
export function ensureOutboundMcpServer(): string {
  const dir = mcpDir();
  mkdirSync(dir, { recursive: true });
  const serverPath = join(dir, "outbound-server.cjs");
  const stampPath = join(dir, ".outbound-version");
  let current = "";
  try { current = readFileSync(stampPath, "utf8").trim(); } catch { /* first run */ }
  if (current !== SERVER_VERSION) {
    writeFileSync(serverPath, OUTBOUND_MCP_SERVER_JS + "\n", { mode: 0o600 });
    writeFileSync(stampPath, SERVER_VERSION, { mode: 0o600 });
  }
  return serverPath;
}

/** The `mcpServers` config object Claude Code reads via `--mcp-config`. Pure. */
export function buildOutboundMcpConfig(nodePath: string, serverPath: string, port: string): {
  mcpServers: Record<string, { command: string; args: string[]; env: Record<string, string> }>;
} {
  return {
    mcpServers: {
      [OUTBOUND_MCP_SERVER_NAME]: {
        command: nodePath,
        args: [serverPath],
        env: { HIVE_DAEMON_PORT: port },
      },
    },
  };
}

/**
 * Materialize the server + write the mcp-config file, returning the config path
 * (for `--mcp-config`) and the tool names (for `--allowedTools`). `nodePath`
 * defaults to the running node so it's valid in dev and in the packaged bundle.
 */
export function prepareOutboundMcp(port = process.env.HIVE_DAEMON_PORT ?? "3747", nodePath = process.execPath): {
  configPath: string;
  toolNames: string[];
} {
  const serverPath = ensureOutboundMcpServer();
  const configPath = join(mcpDir(), "claude-mcp-config.json");
  writeFileSync(configPath, JSON.stringify(buildOutboundMcpConfig(nodePath, serverPath, port), null, 2), { mode: 0o600 });
  return { configPath, toolNames: OUTBOUND_MCP_TOOL_NAMES };
}
