/**
 * build-daemon.mjs — bundle the HiveMatrix daemon into a self-contained runtime
 * that runs with ZERO system dependencies (no system Node, no tsx, no git checkout).
 *
 *   node scripts/build-daemon.mjs
 *
 * Output: dist/daemon/
 *   bin/node                         pinned Node (re-signed later in P5)
 *   daemon.cjs                       esbuild bundle of src/daemon/index.ts
 *   node_modules/better-sqlite3/...  pruned native module (lib + build/Release/*.node)
 *   node_modules/bindings, file-uri-to-path   better-sqlite3's runtime deps
 *   build-info.json                  what was produced
 *
 * Tauri picks dist/daemon up as a bundle resource (see tauri.conf.json
 * bundle.resources) and copies it to HiveMatrix.app/Contents/Resources/daemon/.
 *
 * Native modules are externalized (esbuild can't inline a .node) and shipped on
 * disk so a normal require() resolves them. Everything else (chokidar, dotenv)
 * is inlined into daemon.cjs.
 *
 * Node is PINNED to the version whose ABI matches the prebuilt better_sqlite3.node
 * in node_modules — keep NODE_VERSION in lockstep with the installed Node when the
 * native module is rebuilt.
 */

import { build } from "esbuild";
import {
  rmSync, mkdirSync, cpSync, existsSync, chmodSync, writeFileSync, statSync,
} from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { execFileSync } from "child_process";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src");
const OUT = join(ROOT, "dist", "daemon");
const CACHE = join(ROOT, "dist", ".node-cache");

// Pinned Node. Must match the ABI of node_modules/better-sqlite3/build/Release/
// better_sqlite3.node (run `node -p process.versions.modules` after a rebuild).
const NODE_VERSION = "22.22.3";
const ARCH = "arm64"; // Apple Silicon only (locked decision)
const NODE_DIST = `node-v${NODE_VERSION}-darwin-${ARCH}`;
const NODE_URL = `https://nodejs.org/dist/v${NODE_VERSION}/${NODE_DIST}.tar.gz`;

const NATIVE_EXTERNALS = ["better-sqlite3", "fsevents"];

function log(msg) { console.log(`[build-daemon] ${msg}`); }
function human(bytes) { return `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function dirSize(p) {
  try { return parseInt(execFileSync("du", ["-sk", p]).toString().split("\t")[0], 10) * 1024; }
  catch { return 0; }
}

function gitValue(args, fallback = null) {
  try { return execFileSync("git", args, { cwd: ROOT, encoding: "utf8" }).trim(); }
  catch { return fallback; }
}

// ── 1. Clean output ─────────────────────────────────────────────────────────
log(`output: ${OUT}`);
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

// ── 2. esbuild bundle ────────────────────────────────────────────────────────
// esbuild resolves the `@/*` -> `./src/*` alias natively from tsconfig.json.
log("bundling src/daemon/index.ts -> daemon.cjs");
await build({
  entryPoints: [join(SRC, "daemon", "index.ts")],
  outfile: join(OUT, "daemon.cjs"),
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node22",
  external: NATIVE_EXTERNALS,
  tsconfig: join(ROOT, "tsconfig.json"),
  sourcemap: false,
  legalComments: "none",
  logLevel: "info",
  banner: { js: "// HiveMatrix bundled daemon — generated by scripts/build-daemon.mjs. Do not edit." },
});
log(`daemon.cjs: ${human(statSync(join(OUT, "daemon.cjs")).size)}`);

// ── 3. Stage native modules (externalized — resolved on disk at runtime) ──────
const stagedNM = join(OUT, "node_modules");

// better-sqlite3: prune the heavy deps/ + src/ + build intermediates; keep only
// what's needed at runtime: package.json, lib/, build/Release/better_sqlite3.node.
log("staging better-sqlite3 (pruned)");
const bs3Out = join(stagedNM, "better-sqlite3");
mkdirSync(join(bs3Out, "build", "Release"), { recursive: true });
cpSync(join(ROOT, "node_modules", "better-sqlite3", "package.json"), join(bs3Out, "package.json"));
cpSync(join(ROOT, "node_modules", "better-sqlite3", "lib"), join(bs3Out, "lib"), { recursive: true });
const addon = join(ROOT, "node_modules", "better-sqlite3", "build", "Release", "better_sqlite3.node");
if (!existsSync(addon)) {
  console.error(`✗ ${addon} not found — run \`npm rebuild better-sqlite3\` under Node ${NODE_VERSION} first.`);
  process.exit(1);
}
cpSync(addon, join(bs3Out, "build", "Release", "better_sqlite3.node"));

// better-sqlite3's runtime deps (tiny): bindings -> file-uri-to-path.
for (const dep of ["bindings", "file-uri-to-path"]) {
  const from = join(ROOT, "node_modules", dep);
  if (!existsSync(from)) { console.error(`✗ node_modules/${dep} missing`); process.exit(1); }
  log(`staging ${dep}`);
  cpSync(from, join(stagedNM, dep), { recursive: true });
}

// ── 4. Stage the pinned Node binary (download + cache) ────────────────────────
const cachedNode = join(CACHE, NODE_DIST, "bin", "node");
if (!existsSync(cachedNode)) {
  log(`downloading Node ${NODE_VERSION} (${ARCH})…`);
  mkdirSync(CACHE, { recursive: true });
  const tarball = join(CACHE, `${NODE_DIST}.tar.gz`);
  execFileSync("curl", ["-fSL", "-o", tarball, NODE_URL], { stdio: "inherit" });
  execFileSync("tar", ["-xzf", tarball, "-C", CACHE], { stdio: "inherit" });
  if (!existsSync(cachedNode)) { console.error(`✗ ${cachedNode} not found after extract`); process.exit(1); }
}
log("staging bin/node");
mkdirSync(join(OUT, "bin"), { recursive: true });
cpSync(cachedNode, join(OUT, "bin", "node"));
chmodSync(join(OUT, "bin", "node"), 0o755);

// ── 5. Build info ─────────────────────────────────────────────────────────────
const info = {
  generatedAt: new Date().toISOString().replace(/\.\d+Z$/, "Z"),
  sourceCommit: gitValue(["rev-parse", "HEAD"]),
  sourceDirty: !!gitValue(["status", "--porcelain"], ""),
  nodeVersion: NODE_VERSION,
  arch: ARCH,
  externals: NATIVE_EXTERNALS,
  totalSize: human(dirSize(OUT)),
};
writeFileSync(join(OUT, "build-info.json"), JSON.stringify(info, null, 2) + "\n");
log(`done. total: ${info.totalSize}`);
log(`run: HIVEMATRIX_NODE_BIN=${join(OUT, "bin", "node")} ${join(OUT, "bin", "node")} ${join(OUT, "daemon.cjs")}`);
