/**
 * Release notes — the browsable changelog surfaced in the console (Release notes
 * view) and GET /releases. SOURCE OF TRUTH for both; CHANGELOG.md is generated
 * from this by scripts/gen-changelog.mjs. scripts/release-version.mjs (driven by
 * scripts/developer-id-release.sh) prepends a new entry on each release. Newest first.
 */

export interface ReleaseNote {
  version: string;
  date: string; // YYYY-MM-DD
  note: string; // one-line summary ('' = maintenance release)
}

export const CHANGELOG: ReleaseNote[] = [
  { version: "0.1.221", date: "2026-07-18", note: "Fixes the update indicator going dark while an update really was published. The version check cached a failed fetch exactly like a successful one, so a single transient network timeout pinned 'no update available' for a full minute and every poll in that window re-served the stale failure — which is why 0.1.220 looked like it was never staged even though it was live on the feed the whole time. Failed checks now expire in seconds so the next poll retries, while successful checks keep their normal cache. Also records the outstanding work from this run in docs/open-items-2026-07-18.md, including three debugging facts that each cost real time: the exact launch arguments of a run are stored on the task itself rather than inferred from the process list, browser sign-in recipes live under a differently-named field than you would guess, and building the iOS app for the simulator fails on the embedded watch target." },
  { version: "0.1.220", date: "2026-07-18", note: "Agents no longer clobber each other's work. Everything here runs against one shared checkout — you, and every task agent — and finished-but-unreviewed work routinely sits uncommitted in it. A blanket 'git add -A' therefore sweeps someone else's feature into an unrelated commit under an unrelated message, which is exactly what happened: roughly 900 lines of a finished console feature were absorbed into a harness fix and would have shipped inside an unrelated release, caught only because the release script refuses to build off a non-main branch. Agents are now told, in the file every coding agent reads and again in the task itself, to stage only the files they touched, to commit their own work before finishing so it cannot be swept, and never to merge or resolve conflicts. Integration is now a mechanical fast-forward-only step that refuses on a dirty tree or a diverged branch and hands the decision back to you, because a merge needs the intent of both sides and an agent only ever authored one." },
  { version: "0.1.219", date: "2026-07-18", note: "Two harness fixes found by inspecting a live run rather than trusting the tests. The adaptive effort default shipped two releases ago was never actually reaching the CLI: the spawn path handed it an already-resolved thinking mode, which collapses 'auto' to maximum reasoning, so every task still launched pinned at max — the exact slowness that change was meant to remove. Confirmed against a running agent started seconds after the previous release, which still carried the max flag. The unit tests had passed throughout because they exercised the argument builder directly and nothing covered the real call site; there is now a guard on the call site itself. Separately, the delegation instruction hardcoded specific model tiers, telling a Sonnet-routed agent that it was Opus and should hand work to Sonnet subagents — i.e. to itself. It is now model-agnostic, since the router chooses the tier and any hardcoded name can only drift from reality." },
  { version: "0.1.218", date: "2026-07-18", note: "Tasks you escalate from chat now land in the repo you actually named. A request that explicitly said 'in hivematrix-ios' was filed against the daemon repo instead, which means the coding agent opens the wrong checkout, cannot find the files it was asked to change, and either fails or edits the wrong project — silently wasting the run. Flash must now pass exactly the repo you name and cannot substitute a similarly-named one. Also drops a stale example that pointed at the deprecated standalone watch repo, which can no longer ship; the watch app lives inside the iOS app." },
  { version: "0.1.217", date: "2026-07-18", note: "Approvals are now actionable from the lock screen and the wrist. The daemon tags approval pushes with an actionable category, which is what makes iOS render Approve/Deny directly on the notification instead of plain text you have to unlock and chase. Paired with HiveMatrix iOS build 62 (uploaded to TestFlight): the phone app previously had no notification delegate at all, so a push arriving while the app was open was silently dropped and tapping one did nothing — now taps deep-link straight to the approval queue and the Approve/Deny buttons resolve without opening the app. The Watch gains an approvals screen (its API had been wired but unreachable) and a complication that shows how many approvals are waiting, so the watch face itself tells you when the loop is blocked on you." },
  { version: "0.1.216", date: "2026-07-18", note: "Live agent output now actually streams to the console. AgentManager broadcast every text delta, tool event and error to a listener that was never wired up — the field stayed the empty no-op it was initialised with, so all live output was discarded and the console's only way to learn an agent had produced anything was its 5-second backstop poll. That single dead wire is why generation appeared to arrive in 5-second chunks regardless of how fast the model streamed; it was never a rendering or model problem. Agent text now pushes an event the console already listens for, on the existing 500ms flush rather than per token, so first visible output lands in about half a second instead of up to five, without a refresh storm and with the broadcast failure-isolated so it can never break a run." },
  { version: "0.1.215", date: "2026-07-18", note: "Message Lane sends again, and Apple sign-ins actually complete. Message Lane: two failures were hiding behind one generic error — an intermittent macOS -1719 where Messages' account list enumerates empty (added a chat-id recovery path using the service-agnostic 'any;-;' prefix), and an unanswered Automation consent prompt after an app update that surfaced as a silent 30s timeout (send failures now distinguish TIMEOUT from a real AppleScript error and keep stderr/exit code, so they can never go opaque again). Browser Lane: credential fill now focuses and blurs the field, which is what Apple ID requires before it will enable its Continue button — a filled email next to a dead Continue button was the symptom. Apple Developer gains a login recipe (Apple's ID form lives in a cross-origin iframe on idmsa.apple.com, now allow-listed). Claude Code generation: 'auto' effort no longer collapses to maximum reasoning — the CLI picks its own depth per turn like a direct session, with explicit tiers still available per task, and the delegate-to-subagents directive now applies only to broad self-planning work instead of every trivial task. Time-to-first-token is now recorded per run. One morning message instead of two: the persona-voice brief now carries the Day Brief's real numbers rather than sending a separate robotic contract. Task creation: escalate_to_task no longer invents scope — a spec it wrote had fabricated test targets, re-proposed already-shipped work, and contradicted the standing human-click-only credential rule." },
  { version: "0.1.214", date: "2026-07-18", note: "Faster, less-blocking Claude Code generation and a warmer, more reachable assistant. The coding harness no longer runs its approval hook on read-only tools (Read/Edit/Grep/etc. skip it entirely — verified against the Claude CLI; Bash and MCP tools are still gated exactly as before), reads the autonomy dial live so flipping to Autonomous unblocks an already-running agent on its next tool call, and polls approvals 5x faster. Flash now carries an always-on warm, direct voice (deferring to your SOUL/IDENTITY persona) and writes plain text to iMessage/Mail instead of leaking markdown into text bubbles, and it learns how you like to be talked to over time. Approvals and stuck tasks now push to your phone and watch over APNs/FCM even when the app is closed. The heartbeat now sees your live console/voice conversation so it stops nagging about things you already handled. New Task gains a per-task Effort selector (run simple tasks fast without touching the global default) and Cmd/Ctrl+Enter to submit." },
  { version: "0.1.213", date: "2026-07-18", note: "Browser Lane can now fill logins that live in a cross-origin iframe (App Store Connect / Apple Developer, which sign in through Apple ID on idmsa.apple.com) — the credential is origin-checked against the iframe's real WebKit origin before anything is typed, so it only fills where you allow-listed. Also adds real browser navigation: back / forward / reload-stop with keyboard shortcuts, a load progress bar, copy-URL, open-in-default-browser, and trackpad swipe-to-navigate + pinch-to-zoom." },
  { version: "0.1.212", date: "2026-07-17", note: "Keep one browser alive so sessions survive site switches — signing into a site (Apple ID / App Store Connect especially) no longer logs you out when you switch to another site. Switching sites previously rebuilt the WebKit view and dropped in-memory session cookies and auth state; the browser is now a single persistent instance." },
  { version: "0.1.211", date: "2026-07-17", note: "Browser Lane rebuilt around Canopy's layout: the left sidebar is now the site list itself (session dot, agent-access badge, + add, and a right-click menu for Open / Sign in / Readiness / Edit / Duplicate / Command Log / Delete), a Command Log right panel replaces the Traces screen with per-site audit history and Human/Agent/Blocked/Failed/Security filters, and the remaining chrome moved to toolbar icons that light blue for whichever pane is showing. Multi-step sign-ins now work end to end: an optional per-site login recipe (a fixed click/clickText/waitFor/wait/fill/submit vocabulary, never a script) can drive an OAuth handoff like Samsung Knox, with username/password placeholders substituted natively from the Keychain, an origin check before every credential step, and no reachability from the agent side. HeyGen is no longer hardcoded anywhere — every site is user-defined. Also fixes: a Codable change that would have wiped saved sites, a login runner that deallocated mid-run, stale allowlist checks, unlit toolbar icons, a bottom-anchored Readiness screen, Tab not moving between form fields, and silent read-only refusals that now appear in the log." },
  { version: "0.1.210", date: "2026-07-16", note: "Left sidebar consolidation (lanes/agents setup + monitoring, Board collapse, Brain renamed Memory, Overview removed); console: taller composer + prompt snippets, Tools search fixes, gold active usage toggle; Browser Lane: read/write permission gating + Canopy-parity audit filters, and the Desktop fallback is now driven by Claude instead of a dead local-model gate; tasks: resolve project by name instead of a homedir guess, and the runaway budget backstop raised $10 to $25" },
  { version: "0.1.209", date: "2026-07-16", note: "Browser Lane auto-enables desktop fallback on first authenticated site; Goals auto-seed from persona/GOALS.md; voice fix (no say-voiced chunk on Kokoro failure); console scroll-position restoration for Chat/Tools/Goals" },
  { version: "0.1.208", date: "2026-07-16", note: "Task board: batch grouping + verification-verdict badges; opt-in per-task git worktree isolation (off by default); Tools window search + parameter discovery + run" },
  { version: "0.1.207", date: "2026-07-15", note: "Flash can now inspect its own tasks: ask it 'why did this task fail?' and it reads the task's error + activity log itself (get_task), or 'what's failed/running?' for the board (list_tasks) — no more asking you to screenshot the error." },
  { version: "0.1.206", date: "2026-07-15", note: "Flash chat: paste (Cmd+V) or drag-and-drop an image into the message box — previously only the file picker worked, so pasted screenshots were silently dropped and the assistant couldn't see them." },
  { version: "0.1.205", date: "2026-07-15", note: "Self-improvement loop is now opt-in (default off, toggle in Settings → Features) — it can no longer reinstall or resurrect itself across app updates." },
  { version: "0.1.204", date: "2026-07-15", note: "Message Lane setup fix: the FDA step now shows access you've already granted (it was checking passively and hiding it); restore the allowlist after an update with a backlog-replay guard; home banner for degraded features; voice reads full failed-task errors." },
  { version: "0.1.203", date: "2026-07-15", note: "Message Lane: reveal/restart the real chat.db daemon for Full Disk Access + honest denied copy; DB self-heal restores goals wiped by an update; board status colors (needs-input amber / ready-for-review green); voice approve/deny verb-less follow-up." },
  { version: "0.1.202", date: "2026-07-15", note: "Fix duplicate iMessage sends: one delivery per recipient per run (heals the 2026-07-14 daily-audit double-send); native task execution runs the CLI like a direct Claude Code session (Opus plans, Sonnet builds)." },
  { version: "0.1.201", date: "2026-07-13", note: "Developer ID release" },
  { version: "0.1.200", date: "2026-07-12", note: "Asking about a long document in chat no longer spins up a background task just to finish reading it — the assistant now pages through the whole document directly and answers." },
  { version: "0.1.199", date: "2026-07-12", note: "Voice replies now speak in full — long, multi-paragraph answers (like your solo-founder goals) no longer cut off after the first paragraph, and stay in one consistent voice. Plus: HiveMatrix now texts you when a reminder comes due, so you never miss one even if you don't see the alarm." },
  { version: "0.1.198", date: "2026-07-12", note: "Voice reminders now actually work. Saying 'remind me to call the dentist in 5 minutes' (or any 'remind me…' / 'set a reminder…') over voice now sets a REAL reminder on your devices instead of silently queuing a do-nothing task. Same reliable behavior in chat." },
  { version: "0.1.197", date: "2026-07-12", note: "Fixes 'remind me to X in 5 minutes' (and calendar events) failing silently in chat and streaming voice. The reminders/calendar helper was rejecting timestamps that carried milliseconds, so every timed reminder quietly failed and voice fell back to queuing a do-nothing task. Reminders and events with a time now set reliably." },
  { version: "0.1.196", date: "2026-07-12", note: "The assistant can now SEE photos — attach one in chat (📎) or text one over iMessage and it describes/acts on it. HiveMatrix is now proactive by default: morning/evening briefs, an unprompted heartbeat, and weekly reviews; overdue goals surface in the brief; and recurring accountability rituals no longer silently die. Plus the iPad 'reconnecting' indicator is fixed." },
  { version: "0.1.195", date: "2026-07-12", note: "Voice calendar commands now parse dates correctly too (matching the chat-side fix): 'set an event July 19 at 3pm' lands on the right day and time." },
  { version: "0.1.194", date: "2026-07-12", note: "New Goals surface: track long-horizon goals (Solo Founder, fitness, Italian, Bible) with per-cadence check-ins and a 'due today' review — from the 🎯 Goals panel or in chat. Plus a calendar date-parsing fix so 'July 19 at 3 PM' lands on the right day and time." },
  { version: "0.1.193", date: "2026-07-12", note: "Drop a YouTube link into chat (digest_url) and get a rich HTML summary saved to your brain: clickable video link, thumbnail, a detailed transcript-based summary, and a 'how this applies to me' section tied to HiveMatrix and your Solo Founder goals." },
  { version: "0.1.192", date: "2026-07-12", note: "Observability redesigned: the full dashboard now takes over the center like New Task, tokens-by-model shows side-by-side bars so you can see which model you use most, and the scorecard is per-model (Opus/Sonnet/Haiku/Codex) with first-pass rate and cost per task." },
  { version: "0.1.191", date: "2026-07-12", note: "New Tools panel shows every capability the assistant has and what backs it; curated skills are now first-class tools; reminders read/create moved to the reliable EventKit helper (needs a one-time Reminders permission grant)." },
  { version: "0.1.190", date: "2026-07-12", note: "Chat now reads your goals/plans (brain_read), unified voice+chat thread with task-completion posted back, dictation mic auto-sends, calendar access fixed (helper rebuilt), Talk button retired, qwen removed." },
  { version: "0.1.189", date: "2026-07-12", note: "Chat backlog: observability by-model graphs + Flash usage now tracked, chat honors the Autonomy dial, microphone fixed with a dictation mic above Send, MCP servers and Canopy now visible in setup." },
  { version: "0.1.188", date: "2026-07-12", note: "Learning pipeline hardened: skills with embedded code no longer get truncated during authoring, and the assistant prefers learning a quick script over driving the GUI for computable tasks." },
  { version: "0.1.187", date: "2026-07-12", note: "Learning resilience: a momentary model-call failure no longer cancels skill learning — HiveMatrix retries and finishes the job." },
  { version: "0.1.186", date: "2026-07-12", note: "Smarter learning: when a freshly-learned skill fails its own tests, HiveMatrix now retries once with the exact failure in hand, tests are written to pass on any machine, and failure details are kept for the next attempt." },
  { version: "0.1.185", date: "2026-07-12", note: "Honesty gate: the assistant can no longer fake a tool call and invent results — fabricated replies are discarded and it offers to learn a real skill instead; tool failures now trigger skill learning rather than asking you to do it by hand." },
  { version: "0.1.184", date: "2026-07-12", note: "Voice never dead-ends: when a tool fails, HiveMatrix now learns a new skill for the task instead of asking you to do it by hand; permission blocks get spoken remediation." },
  { version: "0.1.183", date: "2026-07-12", note: "Calendar first-run polish: while macOS's calendar-permission prompt is pending, HiveMatrix now says exactly how to grant access instead of a generic failure." },
  { version: "0.1.182", date: "2026-07-12", note: "Self-learning: calendar reads via EventKit (no more app-launch dead-end), skill_run lets voice/chat execute learned skills in a sandbox, learn_skill acquires+verifies new skills live on capability misses, 'update HiveMatrix to X' routes to the coding pipeline, background gap→skill acquisition under autonomous mode, morning brief reports what it learned." },
  { version: "0.1.181", date: "2026-07-12", note: "Cloudflare pairing QR: fix the display overflow (it was overlapping the security note and corrupting the scannable quiet zone) and make the dense QR scannable — constrain the SVG to its box, enlarge it 188→240px, and render at error-correction level L for bigger modules." },
  { version: "0.1.180", date: "2026-07-11", note: "Flash chat: remove the thumbs-down button, mark the assistant with the cyclone sigil; refresh the Cloudflare card copy to point at the Scan-on-iPhone pairing QR." },
  { version: "0.1.179", date: "2026-07-11", note: "Polish + Browser Lane fix: Observability hides retired local models (Claude-only) with by-model tiers; single live header indicator (dropped cloud-ok pill); provider On/Off toggles replaced by install/sign-in status (enablement = CLI detected); new Cloudflare pairing QR endpoint + card; Flash --resume session continuity with live streaming; and flash chat now disables the CLI's built-in tools so web reads route through Browser Lane instead of dead-ending on WebFetch." },
  { version: "0.1.178", date: "2026-07-11", note: "Fix Flash chat crash on any multi-turn conversation: the prompt is now piped via stdin instead of an argv value, so a prompt beginning with the '--- Prior conversation ---' transcript block is no longer mis-parsed by the claude CLI as an unknown option." },
  { version: "0.1.177", date: "2026-07-11", note: "Post-cutover cleanup: purge all remaining local/Qwen/Rapid-MLX UI from settings; Observability now breaks down by Claude model (Opus/Sonnet/Haiku/Codex) + 1h chart fix; Mail Lane TCC probe + auto retry so approval actually works; New Task no longer forces a Project (operations tasks run from home); retire Terminal Lane entirely (moved to Canopy); default model simplified to Opus/Sonnet (default Sonnet)." },
  { version: "0.1.176", date: "2026-07-11", note: "Claude-native cutover: retire local Qwen entirely — every text role routes to Claude via the CLI (Opus=thinking, Sonnet=coding, Haiku=operational + chat). Flash chat on Haiku with lane tools as an MCP server; degeneration guards deleted; Local Model settings → Claude Models routing view; one-time config migration drops qwen/localEngine keys." },
  { version: "0.1.175", date: "2026-07-11", note: "Flash sampling: add top_k=20 (the honored anti-degeneration lever rapid-mlx was missing), expose full sampling param set in settings with a one-click Qwen-recommended preset" },
  { version: "0.1.174", date: "2026-07-11", note: "Flash: catch repetition-with-drift degeneration (normalized unit-cycle guard); send repeat_penalty for rapid-mlx; prune drift-loop history" },
  { version: "0.1.173", date: "2026-07-11", note: "Flash chat hardening: length-cap runaway guard for varied rambling, lower default max_tokens (2048→1024), both tunable in Settings > Local Model > Sampling; pruned poisoned chat history" },
  { version: "0.1.172", date: "2026-07-11", note: "Fix Flash chat degeneration (word-loop repetition guard + repetition_penalty); expose sampling params (temperature/top_p/repetition_penalty/max_tokens) in Settings > Local Model" },
  { version: "0.1.171", date: "2026-07-11", note: "Voice everywhere: PIM tools (contacts/calendar/reminders read + live reminder/event creation), voice approvals, tap-to-dial actions, loop-closer (voice tasks text their answer back), day-brief rituals + contextual call greeting, capability ratchet, Weaver audit" },
  { version: "0.1.170", date: "2026-07-10", note: "Fix voice license fingerprint mismatch after hostname->hardware-UUID binding change; surface real Pipecat connect errors instead of generic NSError text on iOS" },
  { version: "0.1.169", date: "2026-07-10", note: "Fix daemon launching with cwd=/ (WorkingDirectory missing from launchd plist), causing skill/feedback/directive tasks to get permanently stuck; also fix task-role vs auth-profile field confusion in skill/feedback task creation" },
  { version: "0.1.168", date: "2026-07-10", note: "Fix Tailscale toggle always showing Off in Settings" },
  { version: "0.1.167", date: "2026-07-10", note: "Developer ID release" },
  { version: "0.1.166", date: "2026-07-10", note: "Developer ID release" },
  { version: "0.1.165", date: "2026-07-10", note: "Developer ID release" },
  { version: "0.1.164", date: "2026-07-10", note: "Developer ID release" },
  { version: "0.1.163", date: "2026-07-10", note: "Developer ID release" },
  { version: "0.1.162", date: "2026-07-09", note: "Developer ID release" },
  { version: "0.1.161", date: "2026-07-09", note: "Developer ID release" },
  { version: "0.1.160", date: "2026-07-09", note: "Developer ID release" },
  { version: "0.1.159", date: "2026-07-09", note: "Chat rename, 7-day usage day-ticks, prompt-wizard task titles, task provenance pills" },
  { version: "0.1.158", date: "2026-07-09", note: "Fix: expand '~' projectPath (Inbox project) before task creation, preventing an ENOENT on task spawn" },
  { version: "0.1.157", date: "2026-07-09", note: "Add release-hivematrix skill wrapping canonical developer-id-release.sh" },
  { version: "0.1.156", date: "2026-07-07", note: "Terminal Lane: command policy + audit log; local engine runtime repair; keychain/readiness hardening" },
  { version: "0.1.155", date: "2026-07-07", note: "Fix voice/flash reply repetition loop; add iOS dark + tinted app-icon appearances" },
  { version: "0.1.154", date: "2026-07-07", note: "The router now learns from your re-routes (change a task's model repeatedly for a kind of task and it adopts that as the default). Pipeline self-audit: the accountability layer inspects its own metrics daily and files regressions as feedback — the system watching itself." },
  { version: "0.1.153", date: "2026-07-07", note: "Internal simplification: 12 duplicated poll-loops (Message Lane, Mail Lane, Browser Lane readiness, and background loops) converged onto one shared scaffolding; complexity-budget convention documented for the coding agents. No user-facing behavior change." },
  { version: "0.1.152", date: "2026-07-07", note: "Escalation ladder now tries the other local model (on-device coding specialist) before spending a frontier token — works even offline. Success scoreboard added to the brief: measurable progress against goals (directive criteria proven, weekly task outcomes, first-pass rate). Deep Think now powers local directive planning." },
  { version: "0.1.151", date: "2026-07-07", note: "Deep Think in directive planning: when planning runs on the local model, the plan is produced with test-time compute (diverse rollouts + self-consistency on Qwen) for higher quality — free tokens, latency-tolerant." },
  { version: "0.1.150", date: "2026-07-07", note: "Fixes: duplicate local model removed from the New Task picker (deduped by family); console now auto-reloads after an in-place app update so removed UI (Flights) no longer lingers as a stale page." },
  { version: "0.1.149", date: "2026-07-07", note: "Green-on-white app icon (single identity, no light/dark toggle). Flights/Work Packages removed entirely — broad and multi-step prompts now self-plan via Superpowers (the frontier coding harness plans and executes its own subtasks). New Task Mode is Auto or Direct; Settings simplified." },
  { version: "0.1.148", date: "2026-07-07", note: "Pipeline hardening: ruff static-analysis verification gate + local repair-ladder; local-failure→frontier escalation package; route scorecard + advisory routing bandit; unified decidePolicy approval choke point; frontier-owns-code intake (broad prompts dispatch as one task, Work Packages opt-in); self-aware pipeline health in the heartbeat/brief." },
  { version: "0.1.147", date: "2026-07-06", note: "Use Qwen Rapid-MLX for local chat" },
  { version: "0.1.146", date: "2026-07-06", note: "auto-deploy HiveMatrix" },
  { version: "0.1.145", date: "2026-07-06", note: "Message Lane setup removal controls" },
  { version: "0.1.144", date: "2026-07-06", note: "Message Lane self handles and voice email bridge" },
  { version: "0.1.143", date: "2026-07-06", note: "Simplify voice/video: Kokoro-only TTS; remove the video factory / HeyGen pipeline entirely." },
  { version: "0.1.142", date: "2026-07-05", note: "Developer ID release" },
  { version: "0.1.141", date: "2026-07-05", note: "Developer ID release" },
  { version: "0.1.140", date: "2026-07-05", note: "Fix Tailscale pairing URL: advertise the MagicDNS HTTPS serve endpoint (https://<magicDNS>) instead of a dead loopback-bound http://<tailnet-ip>:port" },
  { version: "0.1.139", date: "2026-07-05", note: "First hivematrix-core.json feed release on the Developer ID identity com.irvcassio.hivematrix.core; new-task box shows pickable command options; arms auto-update for the new identity" },
  { version: "0.1.138", date: "2026-07-05", note: "Fix auto-update so new versions take effect: after install the bundled daemon restarts into the new version, and the daemon self-heals when updated from an older build" },
  { version: "0.1.137", date: "2026-07-05", note: "Fix iOS Talk and Live voice replies" },
  { version: "0.1.136", date: "2026-07-04", note: "Harden inbound pollers and Browser Lane reads: mail/message poll loops log failures instead of swallowing them, and the Browser Lane read client bounds its fetch with a timeout so a hung app fails the read instead of stalling the calling task" },
  { version: "0.1.135", date: "2026-07-04", note: "Proactive-partner layer: heartbeat presence (pulse plus morning brief and evening recap), operator modeling and voice-writable goal ledger, backlog pattern detection, capability self-assessment, autonomy trust-ramp, deep-think reasoning on the local model, and voice deep-think/goals/memory/heartbeat commands; hardened by an adversarial review pass (enforced heartbeat tool gating, continuous learning, contestable trust, atomic config writes)" },
  { version: "0.1.134", date: "2026-07-04", note: "loop-guard smoke verification prevents false-complete coding tasks" },
  { version: "0.1.133", date: "2026-07-04", note: "Local-agent parity experiments: per-request thinking controls over HTTP, loop-aware agent turns, and a gated native local coding harness experiment kept off by default" },
  { version: "0.1.132", date: "2026-07-04", note: "Standardize local models after the tools/model-bench bake-off: Qwen3.6-35B-A3B via Rapid-MLX for lower-memory Macs, fix Mixed-mode routing that ignored the configured local model and pointed Claude sessions at the local endpoint, mandatory code-verification gate on every coding agent, on-demand Qwen3-Embedding-0.6B via Ollama for brain search, and a RAM-aware install-local-model.sh for new machines" },
  { version: "0.1.131", date: "2026-07-04", note: "Maintenance: de-duplicate the 0.1.130 changelog entry that concurrent releases left doubled" },
  { version: "0.1.130", date: "2026-07-04", note: "Fix mobile pairing: the QR now shows a clear reason instead of a blank box when it can't render, Settings reflects saved Cloudflare Access credentials, and saving just the secret no longer wipes the client id; add a local license-issue script (counterpart to license-keygen) and harden messagebee onboarding tests against an installed Pro license" },
  { version: "0.1.129", date: "2026-07-04", note: "Fix slow local-model tasks: forward each task's thinking mode to the local server, give goal decomposition a real 60s timeout, and increase local KV cache budget to stop per-turn prefill re-thrashing" },
  { version: "0.1.128", date: "2026-07-04", note: "Optimize local-model goal decomposition: goal-aware flight intake split, offline local-model support, reasoning token budget" },
  { version: "0.1.127", date: "2026-07-03", note: "Browser Lane and Terminal Lane apps now host the agent read/run backends (127.0.0.1:4011 and :4012) so local-model tasks complete and are watchable in-app; local model health config-matching and test-isolation fix; voice routes to the configured local model" },
  { version: "0.1.126", date: "2026-07-03", note: "Make Codex optional and hide unavailable OpenClaw" },
  { version: "0.1.125", date: "2026-07-03", note: "Fix settings and local model UI" },
  { version: "0.1.124", date: "2026-07-03", note: "cloud-first local model setup" },
  { version: "0.1.123", date: "2026-07-03", note: "lock deep link dependencies" },
  { version: "0.1.122", date: "2026-07-03", note: "ship phase gate ledger" },
  { version: "0.1.121", date: "2026-07-02", note: "Phase 4 outcome packs and companion surfaces" },
  { version: "0.1.120", date: "2026-07-02", note: "auto-deploy HiveMatrix next level spec" },
  { version: "0.1.119", date: "2026-07-02", note: "auto-update rebuild" },
  { version: "0.1.118", date: "2026-07-02", note: "improve Flight autonomy and operator feedback" },
  { version: "0.1.117", date: "2026-07-01", note: "7-day usage bar green-red pacing" },
  { version: "0.1.116", date: "2026-07-01", note: "ship OpenClaw center pane" },
  { version: "0.1.115", date: "2026-07-01", note: "refresh desktop auto-update release" },
  { version: "0.1.114", date: "2026-07-01", note: "Fix Vale voice bridge and Flight duplication" },
  { version: "0.1.113", date: "2026-07-01", note: "ship model routing, voice reminders, usage pacing, and console polish" },
  { version: "0.1.112", date: "2026-06-30", note: "ship OpenClaw chat dock and command project routing" },
  { version: "0.1.111", date: "2026-06-30", note: "complete Flight lanes and guard work-package auto-land" },
  { version: "0.1.110", date: "2026-06-29", note: "auto-deploy HiveMatrix" },
  { version: "0.1.109", date: "2026-06-29", note: "lane-off guards for Mail and Message Lane" },
  { version: "0.1.108", date: "2026-06-29", note: "auto-update console fixes" },
  { version: "0.1.107", date: "2026-06-29", note: "flight child autonomy + one-click decisions" },
  { version: "0.1.106", date: "2026-06-29", note: "about version metadata refresh" },
  { version: "0.1.105", date: "2026-06-29", note: "disabled lane passive probe fix" },
  { version: "0.1.104", date: "2026-06-28", note: "Flight review reply reconciliation" },
  { version: "0.1.103", date: "2026-06-28", note: "Flight loop profiles and release preflight" },
  { version: "0.1.102", date: "2026-06-28", note: "Flight reliability and Goal Flights" },
  { version: "0.1.101", date: "2026-06-28", note: "UI polish and Flight queue fixes" },
  { version: "0.1.100", date: "2026-06-28", note: "" },
  { version: "0.1.99", date: "2026-06-27", note: "" },
  { version: "0.1.98", date: "2026-06-27", note: "Queued-task restart and project picker fixes" },
  { version: "0.1.97", date: "2026-06-27", note: "Main-screen Flights orchestration UX" },
  { version: "0.1.96", date: "2026-06-27", note: "" },
  { version: "0.1.95", date: "2026-06-27", note: "" },
  { version: "0.1.94", date: "2026-06-27", note: "" },
  { version: "0.1.93", date: "2026-06-27", note: "Voice weather inline answers + console UI polish" },
  { version: "0.1.92", date: "2026-06-26", note: "Post-autoupdate Lane app update handling" },
  { version: "0.1.91", date: "2026-06-26", note: "" },
  { version: "0.1.90", date: "2026-06-26", note: "Operator-path hardening: Browser Lane Add Site, lane app Edit menus, video-approval guard, release smoke" },
  { version: "0.1.89", date: "2026-06-26", note: "lane app artifact delivery" },
  { version: "0.1.88", date: "2026-06-26", note: "system readiness repair actions" },
  { version: "0.1.87", date: "2026-06-26", note: "Browser Lane Google SSO, Terminal Lane, voice tools, and console UI updates" },
  { version: "0.1.86", date: "2026-06-26", note: "Browser Lane readiness, workflow inbox, and Terminal Lane cleanup" },
  { version: "0.1.84", date: "2026-06-25", note: "Bee-to-Lane rename: lane-native tools, services, config, central protocol, and refreshed guides" },
  { version: "0.1.83", date: "2026-06-24", note: "video: Approve renders via HeyGen Video Agent by default (slides + annotations + B-roll); failed renders are re-approvable; accuracy guard against invented stats" },
  { version: "0.1.82", date: "2026-06-24", note: "video: render failures (e.g. HeyGen out of credit) now surface on the review task instead of silently closing — retry or cancel" },
  { version: "0.1.81", date: "2026-06-24", note: "video: editing a script now saves & stays in review (approve renders separately) + clear review controls; 'create an AI-news video' routes straight to draft/review" },
  { version: "0.1.80", date: "2026-06-24", note: "browsable Release notes in Settings (changelog of every version + summary), auto-updated each release" },
  { version: "0.1.79", date: "2026-06-24", note: "console: edit drafted scripts in place (Edit the draft button), persistent reply-box resize, copy from Result" },
  { version: "0.1.78", date: "2026-06-24", note: "writer-role model selection (frontier or lock-free) + retire weekly-news as a feature (video factory runs via a directive)" },
  { version: "0.1.77", date: "2026-06-24", note: "video: AI-news script now written by the local model (was a canned template); full script shown at the review checkpoint; agents must review-before-render" },
  { version: "0.1.76", date: "2026-06-24", note: "voice: escalated-task results now return to the open Talk session" },
  { version: "0.1.75", date: "2026-06-23", note: "fix: voice message/text/email requests now escalate to a real task and get sent" },
  { version: "0.1.74", date: "2026-06-23", note: "consistent live Kokoro voice across Talk + iMessage (warm /synth endpoint); cloned voice reserved for produced narration" },
  { version: "0.1.73", date: "2026-06-23", note: "voice escalation + video review hardening + iOS demo fixes" },
  { version: "0.1.72", date: "2026-06-23", note: "" },
  { version: "0.1.71", date: "2026-06-23", note: "" },
  { version: "0.1.70", date: "2026-06-23", note: "" },
  { version: "0.1.69", date: "2026-06-23", note: "" },
  { version: "0.1.68", date: "2026-06-23", note: "" },
  { version: "0.1.67", date: "2026-06-23", note: "" },
  { version: "0.1.66", date: "2026-06-23", note: "" },
  { version: "0.1.65", date: "2026-06-23", note: "" },
  { version: "0.1.63", date: "2026-06-22", note: "voice command layer + console UI overhaul + iOS voice redesign" },
  { version: "0.1.62", date: "2026-06-22", note: "" },
  { version: "0.1.61", date: "2026-06-22", note: "" },
  { version: "0.1.60", date: "2026-06-22", note: "" },
  { version: "0.1.59", date: "2026-06-22", note: "" },
  { version: "0.1.58", date: "2026-06-22", note: "Voice: ask Voice Lane to remind you or add a task and it lands in HiveMatrix; unanswered questions escalate too" },
  { version: "0.1.57", date: "2026-06-21", note: "Voice: ask Voice Lane to read an email, list senders, or summarize your inbox — not just count" },
  { version: "0.1.56", date: "2026-06-20", note: "Voice: consistent ~1s spoken turns (email-tool gate) + Kokoro works out-of-the-box for new installs (espeak via pip)" },
  { version: "0.1.55", date: "2026-06-20", note: "Voice: kill spurious email-tool stalls — every spoken turn is now consistently fast (~1s)" },
  { version: "0.1.54", date: "2026-06-20", note: "Kokoro fast TTS for interactive Talk — ~1s voice turns (was several seconds on the cloned voice)" },
  { version: "0.1.53", date: "2026-06-20", note: "Persistent push-to-talk voice worker — STT+TTS stay warm across turns (no per-turn model reload)" },
  { version: "0.1.52", date: "2026-06-20", note: "grouped new-task model selector" },
  { version: "0.1.51", date: "2026-06-20", note: "two-tier Rapid-MLX routing, coding-tier task selection, reasoning status" },
  { version: "0.1.50", date: "2026-06-20", note: "Rapid-MLX local-engine + live status in Settings" },
  { version: "0.1.49", date: "2026-06-20", note: "voice TTS cache+warmup, Mail Lane voice tool, selectable app icon" },
  { version: "0.1.48", date: "2026-06-19", note: "voice TURN, Matrix theme, hex-flower icon, opacity slider" },
  { version: "0.1.47", date: "2026-06-19", note: "role-model-overrides" },
  { version: "0.1.46", date: "2026-06-19", note: "command layout hotfix" },
  { version: "0.1.45", date: "2026-06-19", note: "attachment provider parity" },
  { version: "0.1.44", date: "2026-06-19", note: "console input cleanup" },
  { version: "0.1.43", date: "2026-06-17", note: "" },
  { version: "0.1.42", date: "2026-06-17", note: "" },
  { version: "0.1.41", date: "2026-06-17", note: "" },
  { version: "0.1.40", date: "2026-06-17", note: "" },
  { version: "0.1.39", date: "2026-06-16", note: "command launcher provenance UI" },
  { version: "0.1.38", date: "2026-06-16", note: "feat: render result tables and Mermaid" },
  { version: "0.1.37", date: "2026-06-16", note: "fix: daemon native runtime ABI" },
  { version: "0.1.36", date: "2026-06-16", note: "fix: command launcher owns project context" },
  { version: "0.1.35", date: "2026-06-16", note: "fix: command launches use selected home project path" },
  { version: "0.1.34", date: "2026-06-16", note: "feat: /uploads endpoint (iOS attachments transfer real bytes to host); steer any in-progress task, not just Codex" },
  { version: "0.1.33", date: "2026-06-15", note: "fix: Mail Lane never auto-replies a Gmail/MCP auth dead-end; task tells agent to attach files via Apple Mail send path, not Gmail" },
  { version: "0.1.32", date: "2026-06-15", note: "fix: strip NUL bytes from spawn argv so AGENTS.md/CLAUDE.md with stray nulls can't crash task launch" },
  { version: "0.1.31", date: "2026-06-15", note: "local commands & skills catalog" },
  { version: "0.1.30", date: "2026-06-15", note: "" },
  { version: "0.1.29", date: "2026-06-15", note: "" },
  { version: "0.1.28", date: "2026-06-15", note: "" },
  { version: "0.1.27", date: "2026-06-15", note: "" },
  { version: "0.1.26", date: "2026-06-14", note: "" },
  { version: "0.1.25", date: "2026-06-14", note: "" },
  { version: "0.1.24", date: "2026-06-14", note: "" },
  { version: "0.1.23", date: "2026-06-14", note: "" },
  { version: "0.1.22", date: "2026-06-14", note: "" },
  { version: "0.1.21", date: "2026-06-14", note: "" },
  { version: "0.1.20", date: "2026-06-14", note: "" },
  { version: "0.1.19", date: "2026-06-14", note: "" },
  { version: "0.1.18", date: "2026-06-14", note: "collapsible console + ops script skills" },
  { version: "0.1.17", date: "2026-06-13", note: "Claude auth login" },
  { version: "0.1.16", date: "2026-06-13", note: "interaction fixes" },
  { version: "0.1.15", date: "2026-06-13", note: "usage refresh" },
  { version: "0.1.14", date: "2026-06-13", note: "focus and Mail Lane fixes" },
  { version: "0.1.13", date: "2026-06-13", note: "updater fixes" },
];
